---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      jkube.io/scm-url: https://github.com/spring-projects/spring-boot/Kubernetes-API
      jkube.io/scm-tag: HEAD
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      expose: "true"
      app: Kubernetes-API
      provider: jkube
      version: 0.0.1-SNAPSHOT
      group: com.labcerebrone
    name: kubernetes-api
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: Kubernetes-API
      provider: jkube
      group: com.labcerebrone
    type: NodePort
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      jkube.io/scm-url: https://github.com/spring-projects/spring-boot/Kubernetes-API
      jkube.io/scm-tag: HEAD
    labels:
      app: Kubernetes-API
      provider: jkube
      version: 0.0.1-SNAPSHOT
      group: com.labcerebrone
    name: kubernetes-api
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: Kubernetes-API
        provider: jkube
        group: com.labcerebrone
    template:
      metadata:
        annotations:
          jkube.io/scm-tag: HEAD
          jkube.io/scm-url: https://github.com/spring-projects/spring-boot/Kubernetes-API
        labels:
          app: Kubernetes-API
          provider: jkube
          version: 0.0.1-SNAPSHOT
          group: com.labcerebrone
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: labcerebrone/kubernetes-api:latest
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
